services:
  ffc-tcg-rules-engine:
    build:
      context: .
      target: production
    image: ffc-tcg-rules-engine
    container_name: ffc-tcg-rules-engine
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-rules-engine-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
