{{- include "ffc-helm-library.container-secret" (list . "ffc-tcg-rules-engine.container-secret") -}}
{{- define "ffc-tcg-rules-engine.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
